variable "vnet_name" {}
variable "address_space" {}
variable "location" {}
variable "resource_group" {}
variable "address_prefix" {}
variable "public_ip" {}
variable "allocation_method" {}
variable "sku" {}
variable "nic_name" {}
variable "ipconfig_name" {}
variable "ipaddress_allocation" {}
variable "account_tier" {}
variable "account_repln" {}
variable "vm_name" {}
variable "vm_size" {}
variable "publisher" {}
variable "offer" {}
variable "vm_sku" {}
variable "vm_version" {}
variable "stor_name" {}
variable "stor_size" {}
variable "caching" {}
variable "create_option" {}
variable "disk_type" {}
variable "comp_name" {}
variable "admin_user" {}
variable "admin_pass" {}
